dofuslab/dofuslab

client/.prettierrc
client/components/EquippedItem.tsx
client/components/Item.tsx
client/components/Layout.tsx
client/components/LoginModal.tsx
client/components/StatTable.tsx
client/graphql/mutations/__generated__/login.ts
client/graphql/mutations/__generated__/logout.ts
client/graphql/mutations/login.graphql
client/graphql/mutations/logout.graphql
client/graphql/queries/__generated__/currentUser.ts
client/graphql/queries/__generated__/items.ts
client/graphql/queries/currentUser.graphql
client/graphql/queries/items.graphql
client/package.json
client/yarn.lock
server/app/__init__.py
server/app/database/model_user.py
server/app/schema.py
server/requirements.txt

Add flask-login and UI for login and logout

---

client/components/SignUpModal.tsx
client/public/static/locales/en/auth.json
server/app/mutation_validation_utils.py

Add confirm password field

---

.vscode/settings.json
client/common/wrappers.tsx
client/components/common/SetHeader.tsx
client/package.json
client/yarn.lock
server/app/__init__.py
server/app/database/model_custom_set.py
server/app/database/model_item.py
server/app/database/model_item_type.py
server/app/database/model_set.py
server/app/database/model_weapon_stat.py
server/app/loaders.py
server/app/schema.py
server/app/utils.py
server/config.py
server/requirements.txt

Add dataloader to reduce DB queries
Some background info: https://docs.graphene-python.org/en/latest/execution/dataloader/

Add dataloader and caching

---

server/app/database/data/pets.json

Updates to yellow piwin and addition of kwyness, kompost, and pingoku

updated missing/incorrect pet data

---

client/components/common/ItemStatsList.tsx
client/components/common/Selector.tsx
client/components/common/SetHeader.tsx
client/components/common/SetSelector.tsx
client/components/common/StatEditor.tsx
client/components/desktop/SetBuilder.tsx
client/pages/equip/[itemSlotId]/index.tsx

Fixes: #88, #89, #90, #91, #92

UI enhancements

---

client/common/constants.ts
client/common/utils.tsx

add 'Pods' to status list

---

client/common/constants.ts
client/components/common/SetHeader.tsx

Fixes: #107 
Also, update the GitHub repository link.

Add default value to inputs to reset properly when customSet changes

---

client/components/desktop/ClassicLeftColumnStats.tsx
client/components/desktop/ClassicSetBuilder.tsx
client/components/desktop/SetBuilder.tsx
client/components/mobile/Home.tsx
client/components/mobile/SetBuilder.tsx
client/pages/index.tsx
client/pages/view/[customSetId].tsx

Fix issues with switching builds, move layout outside of classic switch so it isn't remounted

---

client/components/desktop/ClassicLeftColumnStats.tsx
client/components/desktop/ClassicRightColumnStats.tsx
client/components/desktop/ClassicSetBuilder.tsx

Add elemental damages, reorganize classic layout

---

client/components/common/BuildActions.tsx
client/components/common/DeleteCustomSetModal.tsx
client/components/common/WeaponDamage.tsx
client/components/desktop/Layout.tsx
client/components/desktop/SpellVariantPairCard.tsx
client/package.json
client/yarn.lock

Fixes: #121 
^ This was fixed by upgrading antd
Fixes: #124 
Fixes: #123

Upgrade antd, various bugfixes

---

client/common/utils.tsx
client/components/common/SelectorFilters.tsx
client/components/common/SetHeader.tsx
client/components/mobile/EquippedItemCard.tsx

Fixes: #129 
Fixes: #130 
- Persist class when clicking 'back' from equip item page in classic
- Auto-focus search box when mounting equip item page

Misc Classic UI improvements

---

client/common/utils.tsx

Floor pushback damage calc

---

client/components/common/Selector.tsx

Focus search bar on clicking 'Reset all'

---

client/components/common/FavoritesButton.tsx
client/graphql/mutations/__generated__/login.ts
client/graphql/mutations/__generated__/register.ts
client/graphql/mutations/login.graphql
client/graphql/mutations/register.graphql
client/public/static/locales/en/common.json
client/public/static/locales/fr/common.json

- Translation updates (show item types instead of slot name)
- Fix TS

Rebase, cherry-pick favorites edits

---

server/app/database/model_custom_set.py
server/app/database/model_item_type.py

Prioritize empty slots first when equipping multiple items

---

client/common/utils.tsx
client/common/wrappers.tsx
client/pages/_document.tsx

Dynamically generate og-image

---

client/components/common/Selector.tsx

Use window as target for backtop

---

server/app/schema.py

We kind of already had this "feature" already, but it was half-baked, as when querying for items, we were only searching in all locales for set translations and not item translations, and vice versa when querying for sets. This update should make the behavior more consistent, that searching any locale's item name will return the matching item.

Allow searching in any locale

---

server/app/database/data/item_types.json
server/app/translations/de/LC_MESSAGES/messages.po
server/app/translations/es/LC_MESSAGES/messages.po
server/app/translations/fr/LC_MESSAGES/messages.po
server/app/translations/it/LC_MESSAGES/messages.po
server/app/translations/pt/LC_MESSAGES/messages.po
server/oneoff/sync_item_type.py

Italian translations

---

client/common/utils.tsx

Use encodeURIComponent for preview meta image

---

server/app/database/data/items.json
server/app/database/data/rhineetles.json
server/app/translations/es/LC_MESSAGES/messages.po

Add missing spanish translations from new items, Dofus Effects, Prysm

---

client/common/mixins.ts
client/components/common/ChangePasswordModal.tsx
client/components/common/LoginModal.tsx
client/components/common/MageInputNumber.tsx
client/components/common/MyBuilds.tsx
client/components/common/RequestPasswordResetModal.tsx
client/components/common/SelectorFilters.tsx
client/components/common/SetHeader.tsx
client/components/common/SignUpModal.tsx
client/components/common/StatEditor.tsx
client/pages/reset-password.tsx

Increase font size for inputs on mobile to prevent zoom

---

client/components/common/WeaponDamage.tsx

Fix weapon damage/heal icons

---

client/components/common/SetHeader.tsx
client/pages/index.tsx

Redirect to readonly version of build if non-owner visits
Re-add build tags to mobile version of SetHeader

UI Improvements

---

server/app/database/data/items.json
server/app/database/data/sets.json
server/app/database/data/weapons.json

Updates to 2.62 items
White rat and Black rat sets were overwritten and not remade at the bottom
Everything should conform to the format correctly.

Update adding 2.62 items

---

server/app/database/data/items.json
server/app/database/data/sets.json
server/app/database/data/weapons.json

- Updates strings for all languages
- Pushback resistance and crit resistance have been removed from Relics of the Crimson Dawn (context https://www.dofus.com/fr/forum/1557-discussions-generales/2365519-changelog-beta-2-62)

Adds translations for all 2.62 items, updates new set bonuses

---

server/app/database/data/sets.json

There had been changes to the values on the Relics of the Crimson Dawn.
Context: https://www.dofus.com/fr/forum/1750-dofus/2366107-eternel-conflit

Crimson dawn set stats revision

---

server/oneoff/database_setup.py

I encountered this issue while setting up my dev environment. I believe this is the correct fix for this. Prior to this fix I was getting the following error while populating the database:
[gender_db.log](https://github.com/dofuslab/dofuslab/files/7949286/gender_db.log)

Update to oneoff setup for gendered sprites.

---

README.md
server/app/database/data/items.json
server/app/database/data/sets.json
server/app/database/data/weapons.json

- Adds new items for the 2.63 update
- Adds a section about how to sync items in the database to the readme

Adds new items for the 2.63 update, edits readme

---

server/app/database/data/items.json
server/app/database/data/sets.json

Changes all prysmaradite levels to level 200
Updates sets.json with new 100-150 set bonuses
Reference: https://www.dofus.com/en/mmorpg/news/update/1444581-bosking-evil/details

Updates sets.json with new 100-150 set bonuses

---

server/oneoff/sync_class.py

Adds oneoff script in order to update class spells for newer updates of the game.

Adds oneoff script sync_classes

---

server/app/database/data/item_slots.json
server/app/database/data/item_types.json
server/app/database/data/items.json
server/app/database/data/sets.json
server/app/database/data/weapons.json
server/oneoff/sync_item_type.py

Updates all items except new class set.
Updates slots and types.
Minor fix on sync script.

WIP - Item Updates for 2.66

---

server/app/database/data/buffs.json
server/oneoff/sync_class.py
server/oneoff/update_class_list.py

Adds spells for forgelance and minor changes for others.
Adds update_class_list.py to update the classes in the DB, sync_class uses it to check if there are no new classes in `spells.json` and then acts as normal.

2.66 Forgelance update

---

client/pages/_middleware.ts

Small one liner here, forwarding query params to the redirection :)

Fixes reset password redirection on non-eng languages

---

server/app/database/data/items.json
server/app/database/data/weapons.json

Fixes negative values to perfect, solving the issue of flipped values when there were negative ranges (see Aermyne's Rolling Pin), updates 2.71 items.

Fixes negative values to perfect, updates 2.71 items

---

.vscode/settings.json
server/app/database/data/items.json
server/app/database/data/pets.json
server/app/database/data/sets.json
server/app/database/data/weapons.json

Updated our data .json files from our update script for the 2.72 patch.
Thanks to @Josemanki for catching the issues with our localized set items, this patch fixes those issues as well as the general 2.72 changes.

2.72 Update

---

server/app/database/data/items.json
server/app/database/data/pets.json
server/app/database/data/sets.json
server/app/database/data/translation_files/20241210.json
server/app/database/data/weapons.json

This week's maint's changes, per Survival's API using our scripts on dofuslab-items.

Update for 3.0.15.11.

---

.vscode/settings.json
README.md
docker-compose.yml
server/Dockerfile
server/requirements.txt

This will improve developer experience by not requiring rebuild to make code changes
https://app.screencastify.com/v3/watch/N3OCtzYyXAnuqLfcJVz3

Add Docker compose watch

---

client/pages/build/[customSetId].tsx
server/app/__init__.py
server/app/loaders.py
server/app/schema.py

performance stuff
didn't count the number of queries, but before, there were 2200 lines of logs of queries when logging for sqlalchemy was turned on; this PR reduces that number by 90%!

Add a bunch of dataloaders

---

server/app/database/data/items.json
server/app/database/data/sets.json
server/app/database/data/weapons.json

These are the changes from 3.1, per our scripts on dofuslab-items. Everything looks pretty much okay after I made a tweak to accommodate the change from dofusID to mountDofusID on mounts.

Update for 3.1 via dofuslab-items scripts.
